"""baseline schema

Revision ID: 36e5c04c6f9e
Revises: 
Create Date: 2026-09-17 20:17:00.145565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '36e5c04c6f9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_phone'), 'accounts', ['phone'], unique=True)
    op.create_table('accounts_audit',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('audit_operation', sa.String(length=8), nullable=False),
    sa.Column('audit_actor_id', sa.Uuid(), nullable=True),
    sa.Column('audit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_accounts_audit_actor', 'accounts_audit', ['audit_actor_id', 'audit_at'], unique=False)
    op.create_index('ix_accounts_audit_record', 'accounts_audit', ['id'], unique=False)
    op.create_table('auth_identities_audit',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('audit_operation', sa.String(length=8), nullable=False),
    sa.Column('audit_actor_id', sa.Uuid(), nullable=True),
    sa.Column('audit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_subject', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_auth_identities_audit_actor', 'auth_identities_audit', ['audit_actor_id', 'audit_at'], unique=False)
    op.create_index('ix_auth_identities_audit_record', 'auth_identities_audit', ['id'], unique=False)
    op.create_table('doc_tags_audit',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('audit_operation', sa.String(length=8), nullable=False),
    sa.Column('audit_actor_id', sa.Uuid(), nullable=True),
    sa.Column('audit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('tag_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_doc_tags_audit_actor', 'doc_tags_audit', ['audit_actor_id', 'audit_at'], unique=False)
    op.create_index('ix_doc_tags_audit_record', 'doc_tags_audit', ['document_id', 'tag_id'], unique=False)
    op.create_table('documents_audit',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('audit_operation', sa.String(length=8), nullable=False),
    sa.Column('audit_actor_id', sa.Uuid(), nullable=True),
    sa.Column('audit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('original_extension', sa.String(length=16), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('doc_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_documents_audit_actor', 'documents_audit', ['audit_actor_id', 'audit_at'], unique=False)
    op.create_index('ix_documents_audit_record', 'documents_audit', ['id'], unique=False)
    op.create_table('groups_audit',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('audit_operation', sa.String(length=8), nullable=False),
    sa.Column('audit_actor_id', sa.Uuid(), nullable=True),
    sa.Column('audit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_groups_audit_actor', 'groups_audit', ['audit_actor_id', 'audit_at'], unique=False)
    op.create_index('ix_groups_audit_record', 'groups_audit', ['id'], unique=False)
    op.create_table('invitations_audit',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('audit_operation', sa.String(length=8), nullable=False),
    sa.Column('audit_actor_id', sa.Uuid(), nullable=True),
    sa.Column('audit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('invited_user_id', sa.Uuid(), nullable=True),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_invitations_audit_actor', 'invitations_audit', ['audit_actor_id', 'audit_at'], unique=False)
    op.create_index('ix_invitations_audit_record', 'invitations_audit', ['id'], unique=False)
    op.create_table('memberships_audit',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('audit_operation', sa.String(length=8), nullable=False),
    sa.Column('audit_actor_id', sa.Uuid(), nullable=True),
    sa.Column('audit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_memberships_audit_actor', 'memberships_audit', ['audit_actor_id', 'audit_at'], unique=False)
    op.create_index('ix_memberships_audit_record', 'memberships_audit', ['group_id', 'user_id'], unique=False)
    op.create_table('otp_attempts',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('phone')
    )
    op.create_table('otp_attempts_audit',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('audit_operation', sa.String(length=8), nullable=False),
    sa.Column('audit_actor_id', sa.Uuid(), nullable=True),
    sa.Column('audit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_otp_attempts_audit_actor', 'otp_attempts_audit', ['audit_actor_id', 'audit_at'], unique=False)
    op.create_index('ix_otp_attempts_audit_record', 'otp_attempts_audit', ['phone'], unique=False)
    op.create_table('plan_limits_audit',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('audit_operation', sa.String(length=8), nullable=False),
    sa.Column('audit_actor_id', sa.Uuid(), nullable=True),
    sa.Column('audit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('daily_upload_cap', sa.Integer(), nullable=True),
    sa.Column('max_upload_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('group_member_cap', sa.Integer(), nullable=True),
    sa.Column('soft_delete_retention_days', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_plan_limits_audit_actor', 'plan_limits_audit', ['audit_actor_id', 'audit_at'], unique=False)
    op.create_index('ix_plan_limits_audit_record', 'plan_limits_audit', ['account_id'], unique=False)
    op.create_table('share_grants_audit',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('audit_operation', sa.String(length=8), nullable=False),
    sa.Column('audit_actor_id', sa.Uuid(), nullable=True),
    sa.Column('audit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('permission', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_share_grants_audit_actor', 'share_grants_audit', ['audit_actor_id', 'audit_at'], unique=False)
    op.create_index('ix_share_grants_audit_record', 'share_grants_audit', ['id'], unique=False)
    op.create_table('subscriptions_audit',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('audit_operation', sa.String(length=8), nullable=False),
    sa.Column('audit_actor_id', sa.Uuid(), nullable=True),
    sa.Column('audit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('feature_key', sa.String(length=64), nullable=True),
    sa.Column('credit_balance', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_subscriptions_audit_actor', 'subscriptions_audit', ['audit_actor_id', 'audit_at'], unique=False)
    op.create_index('ix_subscriptions_audit_record', 'subscriptions_audit', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_label'), 'tags', ['label'], unique=True)
    op.create_table('tags_audit',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('audit_operation', sa.String(length=8), nullable=False),
    sa.Column('audit_actor_id', sa.Uuid(), nullable=True),
    sa.Column('audit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_tags_audit_actor', 'tags_audit', ['audit_actor_id', 'audit_at'], unique=False)
    op.create_index('ix_tags_audit_record', 'tags_audit', ['id'], unique=False)
    op.create_table('upload_quotas_audit',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('audit_operation', sa.String(length=8), nullable=False),
    sa.Column('audit_actor_id', sa.Uuid(), nullable=True),
    sa.Column('audit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('files_used_today', sa.Integer(), nullable=True),
    sa.Column('period_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cap_files', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_upload_quotas_audit_actor', 'upload_quotas_audit', ['audit_actor_id', 'audit_at'], unique=False)
    op.create_index('ix_upload_quotas_audit_record', 'upload_quotas_audit', ['account_id'], unique=False)
    op.create_table('auth_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('password', 'otp', 'google', 'apple', name='auth_provider'), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('secret_hash', sa.String(length=256), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'provider', name='uq_auth_account_provider'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_auth_provider_subject')
    )
    op.create_index(op.f('ix_auth_identities_account_id'), 'auth_identities', ['account_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_extension', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('doc_type', sa.Enum('aadhaar', 'voter_id', 'pan', 'passport', 'other', name='document_type'), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index('ix_documents_owner_active', 'documents', ['owner_id', 'deleted_at'], unique=False)
    op.create_index('ix_documents_owner_created', 'documents', ['owner_id', 'created_at'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_limits',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('daily_upload_cap', sa.Integer(), nullable=True),
    sa.Column('max_upload_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('group_member_cap', sa.Integer(), nullable=True),
    sa.Column('soft_delete_retention_days', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('credit_balance', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credit_balance >= 0', name='ck_subscription_credit_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'feature_key', name='uq_subscription_account_feature')
    )
    op.create_index(op.f('ix_subscriptions_account_id'), 'subscriptions', ['account_id'], unique=False)
    op.create_table('upload_quotas',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('files_used_today', sa.Integer(), nullable=False),
    sa.Column('period_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cap_files', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('access_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('upload', 'view', 'download', 'share', 'revoke', 'delete', 'restore', 'rename', name='access_event_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_logs_document_created', 'access_logs', ['document_id', 'created_at'], unique=False)
    op.create_table('doc_tags',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('invited_user_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='invitation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_user_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'invited_user_id', name='uq_invitation_group_user')
    )
    op.create_index(op.f('ix_invitations_group_id'), 'invitations', ['group_id'], unique=False)
    op.create_index(op.f('ix_invitations_invited_user_id'), 'invitations', ['invited_user_id'], unique=False)
    op.create_table('memberships',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='membership_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('share_grants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.Enum('view', 'download', name='share_permission'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_share_grants_document_active', 'share_grants', ['document_id', 'revoked_at'], unique=False)
    op.create_index('ix_share_grants_group_active', 'share_grants', ['group_id', 'revoked_at'], unique=False)
    op.create_index('uq_share_grants_active', 'share_grants', ['document_id', 'group_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'), sqlite_where=sa.text('revoked_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_share_grants_active', table_name='share_grants', postgresql_where=sa.text('revoked_at IS NULL'), sqlite_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_share_grants_group_active', table_name='share_grants')
    op.drop_index('ix_share_grants_document_active', table_name='share_grants')
    op.drop_table('share_grants')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_invitations_invited_user_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_group_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_table('doc_tags')
    op.drop_index('ix_access_logs_document_created', table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_table('upload_quotas')
    op.drop_index(op.f('ix_subscriptions_account_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('plan_limits')
    op.drop_table('groups')
    op.drop_index('ix_documents_owner_created', table_name='documents')
    op.drop_index('ix_documents_owner_active', table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_auth_identities_account_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index('ix_upload_quotas_audit_record', table_name='upload_quotas_audit')
    op.drop_index('ix_upload_quotas_audit_actor', table_name='upload_quotas_audit')
    op.drop_table('upload_quotas_audit')
    op.drop_index('ix_tags_audit_record', table_name='tags_audit')
    op.drop_index('ix_tags_audit_actor', table_name='tags_audit')
    op.drop_table('tags_audit')
    op.drop_index(op.f('ix_tags_label'), table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_subscriptions_audit_record', table_name='subscriptions_audit')
    op.drop_index('ix_subscriptions_audit_actor', table_name='subscriptions_audit')
    op.drop_table('subscriptions_audit')
    op.drop_index('ix_share_grants_audit_record', table_name='share_grants_audit')
    op.drop_index('ix_share_grants_audit_actor', table_name='share_grants_audit')
    op.drop_table('share_grants_audit')
    op.drop_index('ix_plan_limits_audit_record', table_name='plan_limits_audit')
    op.drop_index('ix_plan_limits_audit_actor', table_name='plan_limits_audit')
    op.drop_table('plan_limits_audit')
    op.drop_index('ix_otp_attempts_audit_record', table_name='otp_attempts_audit')
    op.drop_index('ix_otp_attempts_audit_actor', table_name='otp_attempts_audit')
    op.drop_table('otp_attempts_audit')
    op.drop_table('otp_attempts')
    op.drop_index('ix_memberships_audit_record', table_name='memberships_audit')
    op.drop_index('ix_memberships_audit_actor', table_name='memberships_audit')
    op.drop_table('memberships_audit')
    op.drop_index('ix_invitations_audit_record', table_name='invitations_audit')
    op.drop_index('ix_invitations_audit_actor', table_name='invitations_audit')
    op.drop_table('invitations_audit')
    op.drop_index('ix_groups_audit_record', table_name='groups_audit')
    op.drop_index('ix_groups_audit_actor', table_name='groups_audit')
    op.drop_table('groups_audit')
    op.drop_index('ix_documents_audit_record', table_name='documents_audit')
    op.drop_index('ix_documents_audit_actor', table_name='documents_audit')
    op.drop_table('documents_audit')
    op.drop_index('ix_doc_tags_audit_record', table_name='doc_tags_audit')
    op.drop_index('ix_doc_tags_audit_actor', table_name='doc_tags_audit')
    op.drop_table('doc_tags_audit')
    op.drop_index('ix_auth_identities_audit_record', table_name='auth_identities_audit')
    op.drop_index('ix_auth_identities_audit_actor', table_name='auth_identities_audit')
    op.drop_table('auth_identities_audit')
    op.drop_index('ix_accounts_audit_record', table_name='accounts_audit')
    op.drop_index('ix_accounts_audit_actor', table_name='accounts_audit')
    op.drop_table('accounts_audit')
    op.drop_index(op.f('ix_accounts_phone'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
