"""File storage.

All file I/O goes through `StorageBackend`, so the backend can change without
touching business logic — GCS is the primary backend; local disk remains for
development and for a bare checkout without GCP credentials. The PRD also
asks that storage stay swappable for a future peer-to-peer option (§5).

Backends store opaque bytes. Encryption happens above this layer
(`shared.encryption`), so a backend only ever sees ciphertext.

Keys are generated by the server (`documents/<uuid>/original`), never taken
from user input. LocalStorage still refuses any key that would resolve outside
its root, as a second line of defence against path traversal — GCS keys are
just strings passed to an API call, so that guard has no analogue there.

`get_storage()` returns a process-wide singleton, not a fresh instance per
call: constructing a GCS client does real work (credential resolution, HTTP
session setup), so it's built once, lazily, on first use.
"""

import asyncio
import os
from abc import ABC, abstractmethod
from pathlib import Path

from google.api_core.exceptions import NotFound
from google.cloud import storage as gcs

from app.config import settings


class StorageBackend(ABC):
    @abstractmethod
    async def put(self, key: str, data: bytes) -> None:
        """Store bytes under `key`, replacing anything already there."""

    @abstractmethod
    async def get(self, key: str) -> bytes:
        """Return the bytes at `key`. Raises FileNotFoundError if absent."""

    @abstractmethod
    async def delete(self, key: str) -> None:
        """Remove `key`. Deleting a missing key is not an error."""


class LocalStorage(StorageBackend):
    """Stores files under a directory on the local disk. Development only."""

    def __init__(self, root: str) -> None:
        self.root = Path(root).resolve()

    def _path_for(self, key: str) -> Path:
        path = (self.root / key).resolve()
        if path != self.root and self.root not in path.parents:
            raise ValueError("Storage key resolves outside the storage root")
        return path

    async def put(self, key: str, data: bytes) -> None:
        path = self._path_for(key)

        def _write() -> None:
            path.parent.mkdir(parents=True, exist_ok=True)
            # Write-then-rename, so a crash mid-write never leaves a partial
            # file at the real key.
            tmp = path.with_name(path.name + ".tmp")
            tmp.write_bytes(data)
            os.replace(tmp, path)

        await asyncio.to_thread(_write)

    async def get(self, key: str) -> bytes:
        return await asyncio.to_thread(self._path_for(key).read_bytes)

    async def delete(self, key: str) -> None:
        path = self._path_for(key)
        await asyncio.to_thread(path.unlink, True)


class GCSStorage(StorageBackend):
    """Stores files as objects in a single GCS bucket. The production backend."""

    def __init__(self, bucket_name: str) -> None:
        self._bucket_name = bucket_name
        self._client: gcs.Client | None = None

        # Local dev only: point the client at a service-account key file.
        # Unset in real deployments — Workload Identity/ADC resolves
        # credentials from the attached service account instead.
        if settings.gcs_credentials_path:
            os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = settings.gcs_credentials_path

    def _bucket(self) -> gcs.Bucket:
        if self._client is None:
            self._client = gcs.Client(project=settings.gcs_project_id or None)
        return self._client.bucket(self._bucket_name)

    async def put(self, key: str, data: bytes) -> None:
        # A GCS object write is atomic at the object level — no tmp-file-then-
        # rename dance needed, unlike LocalStorage.
        #
        # content_type is explicit: upload_from_string() defaults to
        # "text/plain" if not given, which would mislabel every object (this
        # is always encrypted ciphertext, never the real document's type —
        # that's a DocVault-app-level concern, decided after decrypt, not a
        # property of the opaque bytes GCS stores). A browser or tool opening
        # the raw object directly would otherwise try to render ciphertext as
        # text and show garbage — which is expected for an encrypted blob,
        # but "text/plain" specifically invites someone to mistake that for a
        # real error rather than "this is encrypted, of course it looks broken."
        await asyncio.to_thread(
            lambda: self._bucket().blob(key).upload_from_string(
                data, content_type="application/octet-stream"
            )
        )

    async def get(self, key: str) -> bytes:
        def _read() -> bytes:
            try:
                # google-cloud-storage's stubs return Any here.
                return bytes(self._bucket().blob(key).download_as_bytes())
            except NotFound as exc:
                raise FileNotFoundError(key) from exc

        return await asyncio.to_thread(_read)

    async def delete(self, key: str) -> None:
        def _delete() -> None:
            try:
                self._bucket().blob(key).delete()
            except NotFound:
                pass  # Deleting a missing key is not an error — matches LocalStorage.

        await asyncio.to_thread(_delete)


_storage_singleton: StorageBackend | None = None


def get_storage() -> StorageBackend:
    global _storage_singleton
    if _storage_singleton is None:
        backend = settings.storage_backend
        if backend == "local":
            _storage_singleton = LocalStorage(settings.local_storage_path)
        elif backend == "gcs":
            _storage_singleton = GCSStorage(settings.gcs_bucket_name)  # type: ignore[arg-type]
        else:
            raise ValueError(f"Unknown STORAGE_BACKEND {backend!r}")
    return _storage_singleton
