"""File storage.

All file I/O goes through `StorageBackend`, so the backend can change without
touching business logic — local disk now, Google Cloud Storage later (tracked
in docs/TRACKER.md). The PRD also asks that storage stay swappable for a future
peer-to-peer option (§5).

Backends store opaque bytes. Encryption happens above this layer
(`shared.encryption`), so a backend only ever sees ciphertext.

Keys are generated by the server (`documents/<uuid>/original`), never taken
from user input. LocalStorage still refuses any key that would resolve outside
its root, as a second line of defence against path traversal.
"""

import asyncio
import os
from abc import ABC, abstractmethod
from pathlib import Path

from app.config import settings


class StorageBackend(ABC):
    @abstractmethod
    async def put(self, key: str, data: bytes) -> None:
        """Store bytes under `key`, replacing anything already there."""

    @abstractmethod
    async def get(self, key: str) -> bytes:
        """Return the bytes at `key`. Raises FileNotFoundError if absent."""

    @abstractmethod
    async def delete(self, key: str) -> None:
        """Remove `key`. Deleting a missing key is not an error."""


class LocalStorage(StorageBackend):
    """Stores files under a directory on the local disk. Development only."""

    def __init__(self, root: str) -> None:
        self.root = Path(root).resolve()

    def _path_for(self, key: str) -> Path:
        path = (self.root / key).resolve()
        if path != self.root and self.root not in path.parents:
            raise ValueError("Storage key resolves outside the storage root")
        return path

    async def put(self, key: str, data: bytes) -> None:
        path = self._path_for(key)

        def _write() -> None:
            path.parent.mkdir(parents=True, exist_ok=True)
            # Write-then-rename, so a crash mid-write never leaves a partial
            # file at the real key.
            tmp = path.with_name(path.name + ".tmp")
            tmp.write_bytes(data)
            os.replace(tmp, path)

        await asyncio.to_thread(_write)

    async def get(self, key: str) -> bytes:
        return await asyncio.to_thread(self._path_for(key).read_bytes)

    async def delete(self, key: str) -> None:
        path = self._path_for(key)
        await asyncio.to_thread(path.unlink, True)


def get_storage() -> StorageBackend:
    backend = settings.storage_backend
    if backend == "local":
        return LocalStorage(settings.local_storage_path)
    if backend == "gcs":
        raise NotImplementedError(
            "The GCS storage backend is not built yet — use STORAGE_BACKEND=local"
        )
    raise ValueError(f"Unknown STORAGE_BACKEND {backend!r}")
